### ISSUE TITLE
Fix commit

### ISSUE THREAD

**Issue by hsynercn** [wspawned/adopt-me#2]
Please don't forget to push your local fix

```js
function getTuple(){
   return [["Bob","asd","test","kkkk"], 24];
}
let x = getTuple();
console.log(x.toString()); // Bob,asd,test,kkkk,24
```

https://github.com/wspawned/adopt-me/blob/e13b7790312dfd1be5cfbcf67327aaf90ba48d37/src/SearchParams.js#L11

**Comment by wspawned** [comment]
Fixledik amk
